import { Schema, Table, Column } from '../../types';

function sqlTypeToGraphQL(sqlType: string, nullable: boolean): string {
  const t = sqlType.toUpperCase().replace(/\(.*\)/, '').trim();
  const map: Record<string, string> = {
    INTEGER: 'Int',
    INT: 'Int',
    BIGINT: 'Int',
    SMALLINT: 'Int',
    TINYINT: 'Int',
    SERIAL: 'Int',
    BIGSERIAL: 'Int',
    FLOAT: 'Float',
    DOUBLE: 'Float',
    REAL: 'Float',
    DECIMAL: 'Float',
    NUMERIC: 'Float',
    MONEY: 'Float',
    BOOLEAN: 'Boolean',
    BOOL: 'Boolean',
    TEXT: 'String',
    VARCHAR: 'String',
    CHAR: 'String',
    NVARCHAR: 'String',
    UUID: 'ID',
    JSON: 'String',
    JSONB: 'String',
    TIMESTAMP: 'String',
    TIMESTAMPTZ: 'String',
    DATE: 'String',
    TIME: 'String',
    DATETIME: 'String',
    BLOB: 'String',
    BYTEA: 'String',
    BINARY: 'String',
  };
  const base = map[t] ?? 'String';
  return nullable ? base : `${base}!`;
}

function toCamelCase(str: string): string {
  return str.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

function toPascalCase(str: string): string {
  const cc = toCamelCase(str);
  return cc.charAt(0).toUpperCase() + cc.slice(1);
}

function toSingular(name: string): string {
  if (name.endsWith('ies')) return name.slice(0, -3) + 'y';
  if (name.endsWith('ses') || name.endsWith('xes')) return name.slice(0, -2);
  if (name.endsWith('s') && !name.endsWith('ss')) return name.slice(0, -1);
  return name;
}

function generateType(table: Table, schema: Schema): string {
  const typeName = toPascalCase(toSingular(table.name));
  const lines: string[] = [];
  lines.push(`type ${typeName} {`);

  for (const col of table.columns) {
    const fieldName = toCamelCase(col.name);
    // Use ID for primary keys
    let gqlType: string;
    if (col.isPrimaryKey) {
      gqlType = 'ID!';
    } else {
      gqlType = sqlTypeToGraphQL(col.type, col.nullable);
    }
    lines.push(`  ${fieldName}: ${gqlType}`);
  }

  // Relation fields for FKs
  for (const fk of table.foreignKeys) {
    const relatedType = toPascalCase(toSingular(fk.referencedTable));
    const fieldName = toCamelCase(toSingular(fk.referencedTable));
    lines.push(`  ${fieldName}: ${relatedType}`);
  }

  lines.push('}');
  return lines.join('\n');
}

function generateInputType(table: Table): string {
  const typeName = toPascalCase(toSingular(table.name));
  const lines: string[] = [];
  lines.push(`input Create${typeName}Input {`);

  for (const col of table.columns) {
    if (col.isPrimaryKey) continue; // Skip PK in create input
    const fieldName = toCamelCase(col.name);
    const gqlType = sqlTypeToGraphQL(col.type, col.nullable || !!col.defaultValue);
    lines.push(`  ${fieldName}: ${gqlType}`);
  }

  lines.push('}');
  lines.push('');

  lines.push(`input Update${typeName}Input {`);
  for (const col of table.columns) {
    if (col.isPrimaryKey) continue;
    const fieldName = toCamelCase(col.name);
    const gqlType = sqlTypeToGraphQL(col.type, true); // All optional in update
    lines.push(`  ${fieldName}: ${gqlType}`);
  }
  lines.push('}');

  return lines.join('\n');
}

function generateQueryFields(table: Table): string[] {
  const typeName = toPascalCase(toSingular(table.name));
  const listName = toCamelCase(table.name);
  const singleName = toCamelCase(toSingular(table.name));
  return [
    `  ${singleName}(id: ID!): ${typeName}`,
    `  ${listName}(limit: Int, offset: Int): [${typeName}!]!`,
  ];
}

function generateMutationFields(table: Table): string[] {
  const typeName = toPascalCase(toSingular(table.name));
  const createName = `create${typeName}`;
  const updateName = `update${typeName}`;
  const deleteName = `delete${typeName}`;
  return [
    `  ${createName}(input: Create${typeName}Input!): ${typeName}!`,
    `  ${updateName}(id: ID!, input: Update${typeName}Input!): ${typeName}`,
    `  ${deleteName}(id: ID!): Boolean!`,
  ];
}

export function generateGraphQLSchema(schema: Schema): string {
  const lines: string[] = [];

  lines.push('# Generated by SchemaViz');
  lines.push(`# Database: ${schema.database}`);
  lines.push(`# Generated at: ${schema.generatedAt}`);
  lines.push('');

  // Types
  for (const table of schema.tables) {
    lines.push(generateType(table, schema));
    lines.push('');
  }

  // Input types
  for (const table of schema.tables) {
    lines.push(generateInputType(table));
    lines.push('');
  }

  // Query type
  lines.push('type Query {');
  for (const table of schema.tables) {
    for (const f of generateQueryFields(table)) {
      lines.push(f);
    }
  }
  lines.push('}');
  lines.push('');

  // Mutation type
  lines.push('type Mutation {');
  for (const table of schema.tables) {
    for (const f of generateMutationFields(table)) {
      lines.push(f);
    }
  }
  lines.push('}');
  lines.push('');

  lines.push('schema {');
  lines.push('  query: Query');
  lines.push('  mutation: Mutation');
  lines.push('}');

  return lines.join('\n');
}
