import { Schema, Table, Column } from '../../types';

// Maps common SQL types to Prisma scalar types
function sqlTypeToPrisma(sqlType: string): string {
  const t = sqlType.toUpperCase().replace(/\(.*\)/, '').trim();
  const map: Record<string, string> = {
    INTEGER: 'Int',
    INT: 'Int',
    BIGINT: 'BigInt',
    SMALLINT: 'Int',
    TINYINT: 'Int',
    SERIAL: 'Int',
    BIGSERIAL: 'BigInt',
    FLOAT: 'Float',
    DOUBLE: 'Float',
    REAL: 'Float',
    DECIMAL: 'Decimal',
    NUMERIC: 'Decimal',
    MONEY: 'Decimal',
    BOOLEAN: 'Boolean',
    BOOL: 'Boolean',
    TEXT: 'String',
    VARCHAR: 'String',
    CHAR: 'String',
    NVARCHAR: 'String',
    CLOB: 'String',
    UUID: 'String',
    JSON: 'Json',
    JSONB: 'Json',
    TIMESTAMP: 'DateTime',
    TIMESTAMPTZ: 'DateTime',
    DATE: 'DateTime',
    TIME: 'DateTime',
    DATETIME: 'DateTime',
    BLOB: 'Bytes',
    BYTEA: 'Bytes',
    BINARY: 'Bytes',
  };
  return map[t] ?? 'String';
}

function toCamelCase(str: string): string {
  return str.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

function toPascalCase(str: string): string {
  const cc = toCamelCase(str);
  return cc.charAt(0).toUpperCase() + cc.slice(1);
}

function toSingular(name: string): string {
  if (name.endsWith('ies')) return name.slice(0, -3) + 'y';
  if (name.endsWith('ses') || name.endsWith('xes')) return name.slice(0, -2);
  if (name.endsWith('s') && !name.endsWith('ss')) return name.slice(0, -1);
  return name;
}

function generatePrismaModel(table: Table, schema: Schema): string {
  const modelName = toPascalCase(toSingular(table.name));
  const lines: string[] = [];

  lines.push(`model ${modelName} {`);

  // Pre-compute single-column unique index columns for @unique attribute
  const singleUniqueColumns = new Set(
    table.indexes
      .filter(i => i.isUnique && i.columns.length === 1)
      .map(i => i.columns[0]),
  );

  // Find FK relations
  const fkColNames = new Set(table.foreignKeys.flatMap(fk => fk.columns));

  for (const col of table.columns) {
    const prismaType = sqlTypeToPrisma(col.type);
    const nullable = col.nullable ? '?' : '';
    const defaultAttr = col.isPrimaryKey && ['Int', 'BigInt'].includes(prismaType)
      ? ' @default(autoincrement())'
      : col.isPrimaryKey && prismaType === 'String'
      ? ' @default(uuid())'
      : '';
    const pkAttr = col.isPrimaryKey ? ' @id' : '';
    // Single-column unique indexes become @unique on the field (not @@unique)
    const uniqueAttr = !col.isPrimaryKey && singleUniqueColumns.has(col.name) ? ' @unique' : '';

    let fieldLine = `  ${toCamelCase(col.name)}  ${prismaType}${nullable}${pkAttr}${uniqueAttr}${defaultAttr}`;

    // Column mapping if name differs from camelCase
    if (toCamelCase(col.name) !== col.name) {
      fieldLine += ` @map("${col.name}")`;
    }

    lines.push(fieldLine);
  }

  // Relation fields for foreign keys
  for (const fk of table.foreignKeys) {
    const refModelName = toPascalCase(toSingular(fk.referencedTable));
    const fieldName = toCamelCase(toSingular(fk.referencedTable));
    lines.push(`  ${fieldName}  ${refModelName} @relation(fields: [${fk.columns.map(toCamelCase).join(', ')}], references: [${fk.referencedColumns.map(toCamelCase).join(', ')}])`);
  }

  // Multi-column unique and non-unique indexes as model-level attributes
  for (const idx of table.indexes) {
    if (idx.isUnique && idx.columns.length > 1) {
      lines.push(`  @@unique([${idx.columns.map(toCamelCase).join(', ')}])`);
    }
    if (!idx.isUnique && idx.columns.length > 0) {
      lines.push(`  @@index([${idx.columns.map(toCamelCase).join(', ')}])`);
    }
  }

  if (table.name !== toPascalCase(toSingular(table.name)).toLowerCase() + 's' &&
      table.name !== toPascalCase(toSingular(table.name)).toLowerCase()) {
    lines.push(`  @@map("${table.name}")`);
  }

  lines.push('}');
  return lines.join('\n');
}

export function generatePrismaSchema(schema: Schema): string {
  const lines: string[] = [];

  lines.push('// Generated by SchemaViz');
  lines.push(`// Database: ${schema.database}`);
  lines.push(`// Generated at: ${schema.generatedAt}`);
  lines.push('');
  lines.push('generator client {');
  lines.push('  provider = "prisma-client-js"');
  lines.push('}');
  lines.push('');
  lines.push('datasource db {');
  lines.push('  provider = "postgresql" // Change to your database type');
  lines.push('  url      = env("DATABASE_URL")');
  lines.push('}');
  lines.push('');

  for (const table of schema.tables) {
    lines.push(generatePrismaModel(table, schema));
    lines.push('');
  }

  return lines.join('\n');
}
